networks:
  backend:

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - backend
    env_file:
      - .env
    environment:
      - spring.r2dbc.url=jdbc:postgresql://postgres:5432/$POSTGRES_DB
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s